# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import miso_tables.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField(db_index=True)),
                ('bid_id', models.IntegerField()),
                ('type_of_bid', models.CharField(max_length=1)),
                ('mw', models.FloatField()),
                ('lmp', models.FloatField()),
                ('date', models.DateField(db_index=True)),
                ('hour_ending', models.SmallIntegerField()),
                ('func_price_1', models.FloatField(null=True)),
                ('func_mw_1', models.FloatField(null=True)),
                ('func_price_2', models.FloatField(null=True)),
                ('func_mw_2', models.FloatField(null=True)),
                ('func_price_3', models.FloatField(null=True)),
                ('func_mw_3', models.FloatField(null=True)),
                ('func_price_4', models.FloatField(null=True)),
                ('func_mw_4', models.FloatField(null=True)),
                ('func_price_5', models.FloatField(null=True)),
                ('func_mw_5', models.FloatField(null=True)),
                ('func_price_6', models.FloatField(null=True)),
                ('func_mw_6', models.FloatField(null=True)),
                ('func_price_7', models.FloatField(null=True)),
                ('func_mw_7', models.FloatField(null=True)),
                ('func_price_8', models.FloatField(null=True)),
                ('func_mw_8', models.FloatField(null=True)),
                ('func_price_9', models.FloatField(null=True)),
                ('func_mw_9', models.FloatField(null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataLoadingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('date_loaded', models.DateField()),
                ('model', models.CharField(choices=[(1, miso_tables.models.Node), (2, miso_tables.models.NPH), (3, miso_tables.models.Bid)], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(max_length=1)),
                ('deprecated', models.BooleanField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NPH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(db_index=True, max_length=255)),
                ('hour_ending', models.SmallIntegerField(db_index=True)),
                ('day', models.DateField(db_index=True)),
                ('rt_value', models.FloatField()),
                ('da_value', models.FloatField()),
                ('dart_value', models.FloatField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
