# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import miso_tables.models


class Migration(migrations.Migration):

    dependencies = [
        ('miso_tables', '0003_auto_20160331_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherforecast',
            old_name='hour',
            new_name='predicted_hour',
        ),
        migrations.RenameField(
            model_name='weatherforecast',
            old_name='prediction_dt',
            new_name='prediction_made_dt',
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='predicted_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataloadinglog',
            name='model',
            field=models.CharField(choices=[(5, miso_tables.models.WeatherForecast)], max_length=3),
        ),
    ]
